version: "3.7"

services:
  nginx-react:
    container_name: nginx-react
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - 8080:80
    environment:
      NODE_ENV: production

  server:
    build: ./node-server/
    environment:
      - PORT=4040
    ports:
      - 4040:4040
    command: node main.js
