# generic local version for basic testing
version: "3.7"

services:
  react_frontend:
    image: ghcr.io/whoigit/alvin-observer-ui:stable
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    networks:
      webservicenet:
        aliases:
          - observer-ui
      default:
    volumes:
      # allows env variables to be injected into production React app after image is built
      - ./configEnv-production.js:/usr/share/nginx/html/configEnv.js
    environment:
      NODE_ENV: production
    #command: npm start

networks:
  webservicenet:
    external: true
    name: webservicenet
